id = "zed-zbr"
name = "zbr"
version = "0.1.0"
schema_version = 1
authors = ["ZBRLang"]
description = "Syntax highlighting and snippets for the ZBR scripting language."
repository = "https://github.com/zbrlang/zbr-extensions"

[grammars.zbr]
repository = "https://github.com/zbrlang/zbr-extensions"
rev = "17eca71fc6070e65b77d3f70d092c5f1fc4b4297"
path = "tree-sitter"
