id = "zed-zbr"
name = "zbr"
version = "0.1.0"
schema_version = 1
authors = ["ZBRLang"]
description = "Syntax highlighting and snippets for the ZBR scripting language."
repository = "https://github.com/zbrlang/zbr-extensions"

[grammars.zbr]
repository = "https://github.com/zbrlang/zbr-extensions"
rev = "5f3d375d74f55c195335d3082e2212bdf03a323c"
path = "tree-sitter"
