/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_header_token1 = 1,
  aux_sym_header_token2 = 2,
  sym_newline = 3,
  sym_comment = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  sym_trigger_name = 7,
  sym_operator = 8,
  sym_argument_separator = 9,
  sym_escape_sequence = 10,
  sym_content = 11,
  sym_bare_z = 12,
  sym_text = 13,
  sym_function_start = 14,
  sym_source_file = 15,
  sym_header = 16,
  sym_function_call = 17,
  sym_trigger_call = 18,
  sym_braced_content = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_function_call_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_header_token1] = "header_name",
  [aux_sym_header_token2] = "header_token2",
  [sym_newline] = "newline",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_trigger_name] = "trigger_name",
  [sym_operator] = "operator",
  [sym_argument_separator] = "argument_separator",
  [sym_escape_sequence] = "escape_sequence",
  [sym_content] = "content",
  [sym_bare_z] = "bare_z",
  [sym_text] = "text",
  [sym_function_start] = "function_name",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_function_call] = "function_call",
  [sym_trigger_call] = "trigger_call",
  [sym_braced_content] = "braced_content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [sym_newline] = sym_newline,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_trigger_name] = sym_trigger_name,
  [sym_operator] = sym_operator,
  [sym_argument_separator] = sym_argument_separator,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_content] = sym_content,
  [sym_bare_z] = sym_bare_z,
  [sym_text] = sym_text,
  [sym_function_start] = sym_function_start,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_function_call] = sym_function_call,
  [sym_trigger_call] = sym_trigger_call,
  [sym_braced_content] = sym_braced_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_trigger_name] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_z] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_function_start] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_call] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_key, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 4,
  [11] = 7,
  [12] = 3,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 16,
  [24] = 17,
  [25] = 19,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 27,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, '\''}, {'*', '`'}, {'b', 'b'}, {'f', 'f'}, {'j', 'l'}, {'q', 'q'}, {'v', 'x'}, {'z', '{'},
  {'}', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '\n', 35,
        '!', 50,
        '#', 51,
        '&', 48,
        '/', 49,
        ';', 46,
        '<', 44,
        '=', 50,
        '>', 44,
        'Z', 81,
        '\\', 28,
        'o', 64,
        '{', 39,
        '|', 77,
        '}', 40,
      );
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 50,
        '&', 48,
        '/', 49,
        ';', 46,
        '<', 44,
        '=', 50,
        '>', 44,
        '\\', 28,
        'o', 64,
        '{', 39,
        '|', 77,
        '}', 40,
      );
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 'Z') ADVANCE(80);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(26);
      if (lookahead == 'd') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 't') ADVANCE(20);
      if ((!eof && set_contains(sym_text_character_set_1, 9, lookahead))) ADVANCE(85);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'g') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'g') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(11);
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 27:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == ';' ||
          lookahead == '\\' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(47);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '/') ADVANCE(82);
      if (lookahead == 'Z') ADVANCE(81);
      if (lookahead == 'o') ADVANCE(84);
      if (lookahead != 0) ADVANCE(85);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'Z') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ';' ||
          lookahead == '\\' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_trigger_name);
      if (lookahead == 'Z') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_trigger_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_trigger_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_argument_separator);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '&') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '=') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == 'd') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(52);
      if (lookahead == 't') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'c') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'e') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'g') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'g') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'h') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'i') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'm') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'n') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'n') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'o') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'o') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'p') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'p') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead == 'y') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'r') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 't') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == 'u') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_content);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ';' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_bare_z);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 'Z') ADVANCE(85);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'Z') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 'Z') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 'Z') ADVANCE(85);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 29, .external_lex_state = 1},
  [2] = {.lex_state = 1, .external_lex_state = 1},
  [3] = {.lex_state = 1, .external_lex_state = 1},
  [4] = {.lex_state = 1, .external_lex_state = 1},
  [5] = {.lex_state = 1, .external_lex_state = 1},
  [6] = {.lex_state = 1, .external_lex_state = 1},
  [7] = {.lex_state = 1, .external_lex_state = 1},
  [8] = {.lex_state = 1, .external_lex_state = 1},
  [9] = {.lex_state = 1, .external_lex_state = 1},
  [10] = {.lex_state = 1, .external_lex_state = 1},
  [11] = {.lex_state = 1, .external_lex_state = 1},
  [12] = {.lex_state = 1, .external_lex_state = 1},
  [13] = {.lex_state = 29, .external_lex_state = 1},
  [14] = {.lex_state = 29, .external_lex_state = 1},
  [15] = {.lex_state = 1, .external_lex_state = 1},
  [16] = {.lex_state = 1, .external_lex_state = 1},
  [17] = {.lex_state = 1, .external_lex_state = 1},
  [18] = {.lex_state = 1, .external_lex_state = 1},
  [19] = {.lex_state = 1, .external_lex_state = 1},
  [20] = {.lex_state = 1, .external_lex_state = 1},
  [21] = {.lex_state = 29, .external_lex_state = 1},
  [22] = {.lex_state = 29, .external_lex_state = 1},
  [23] = {.lex_state = 29, .external_lex_state = 1},
  [24] = {.lex_state = 29, .external_lex_state = 1},
  [25] = {.lex_state = 29, .external_lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 33},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_trigger_name] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_argument_separator] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_content] = ACTIONS(1),
    [sym_bare_z] = ACTIONS(1),
    [sym_function_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym_header] = STATE(13),
    [sym_function_call] = STATE(13),
    [sym_trigger_call] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_header_token1] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_trigger_name] = ACTIONS(11),
    [sym_bare_z] = ACTIONS(9),
    [sym_text] = ACTIONS(13),
    [sym_function_start] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_function_call] = STATE(11),
    [sym_trigger_call] = STATE(11),
    [sym_braced_content] = STATE(11),
    [aux_sym_function_call_repeat1] = STATE(11),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(19),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(23),
    [sym_argument_separator] = ACTIONS(25),
    [sym_escape_sequence] = ACTIONS(25),
    [sym_content] = ACTIONS(23),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym_function_call] = STATE(4),
    [sym_trigger_call] = STATE(4),
    [sym_braced_content] = STATE(4),
    [aux_sym_function_call_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(31),
    [sym_argument_separator] = ACTIONS(33),
    [sym_escape_sequence] = ACTIONS(33),
    [sym_content] = ACTIONS(31),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(35),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(37),
    [sym_argument_separator] = ACTIONS(39),
    [sym_escape_sequence] = ACTIONS(39),
    [sym_content] = ACTIONS(37),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(5)] = {
    [sym_function_call] = STATE(8),
    [sym_trigger_call] = STATE(8),
    [sym_braced_content] = STATE(8),
    [aux_sym_function_call_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(41),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(43),
    [sym_argument_separator] = ACTIONS(45),
    [sym_escape_sequence] = ACTIONS(45),
    [sym_content] = ACTIONS(43),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym_function_call] = STATE(7),
    [sym_trigger_call] = STATE(7),
    [sym_braced_content] = STATE(7),
    [aux_sym_function_call_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(47),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(49),
    [sym_argument_separator] = ACTIONS(51),
    [sym_escape_sequence] = ACTIONS(51),
    [sym_content] = ACTIONS(49),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(7)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(53),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(37),
    [sym_argument_separator] = ACTIONS(39),
    [sym_escape_sequence] = ACTIONS(39),
    [sym_content] = ACTIONS(37),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(8)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(55),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(37),
    [sym_argument_separator] = ACTIONS(39),
    [sym_escape_sequence] = ACTIONS(39),
    [sym_content] = ACTIONS(37),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(9)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(60),
    [sym_trigger_name] = ACTIONS(62),
    [sym_operator] = ACTIONS(65),
    [sym_argument_separator] = ACTIONS(68),
    [sym_escape_sequence] = ACTIONS(68),
    [sym_content] = ACTIONS(65),
    [sym_function_start] = ACTIONS(71),
  },
  [STATE(10)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(74),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(37),
    [sym_argument_separator] = ACTIONS(39),
    [sym_escape_sequence] = ACTIONS(39),
    [sym_content] = ACTIONS(37),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(11)] = {
    [sym_function_call] = STATE(9),
    [sym_trigger_call] = STATE(9),
    [sym_braced_content] = STATE(9),
    [aux_sym_function_call_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(76),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(37),
    [sym_argument_separator] = ACTIONS(39),
    [sym_escape_sequence] = ACTIONS(39),
    [sym_content] = ACTIONS(37),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(12)] = {
    [sym_function_call] = STATE(10),
    [sym_trigger_call] = STATE(10),
    [sym_braced_content] = STATE(10),
    [aux_sym_function_call_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(78),
    [sym_trigger_name] = ACTIONS(21),
    [sym_operator] = ACTIONS(80),
    [sym_argument_separator] = ACTIONS(82),
    [sym_escape_sequence] = ACTIONS(82),
    [sym_content] = ACTIONS(80),
    [sym_function_start] = ACTIONS(27),
  },
  [STATE(13)] = {
    [sym_header] = STATE(14),
    [sym_function_call] = STATE(14),
    [sym_trigger_call] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(84),
    [aux_sym_header_token1] = ACTIONS(7),
    [sym_newline] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
    [sym_trigger_name] = ACTIONS(11),
    [sym_bare_z] = ACTIONS(86),
    [sym_text] = ACTIONS(88),
    [sym_function_start] = ACTIONS(15),
  },
  [STATE(14)] = {
    [sym_header] = STATE(14),
    [sym_function_call] = STATE(14),
    [sym_trigger_call] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(90),
    [aux_sym_header_token1] = ACTIONS(92),
    [sym_newline] = ACTIONS(95),
    [sym_comment] = ACTIONS(3),
    [sym_trigger_name] = ACTIONS(98),
    [sym_bare_z] = ACTIONS(95),
    [sym_text] = ACTIONS(101),
    [sym_function_start] = ACTIONS(104),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(107), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [16] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(111), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [32] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(115), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [48] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(119), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [64] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(123), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [80] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      sym_trigger_name,
      sym_operator,
      sym_content,
    ACTIONS(127), 5,
      sym_function_start,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_argument_separator,
      sym_escape_sequence,
  [96] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      sym_trigger_name,
      sym_text,
    ACTIONS(127), 5,
      sym_function_start,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      sym_newline,
      sym_bare_z,
  [111] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym_trigger_name,
      sym_text,
    ACTIONS(131), 5,
      sym_function_start,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      sym_newline,
      sym_bare_z,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      sym_trigger_name,
      sym_text,
    ACTIONS(111), 5,
      sym_function_start,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      sym_newline,
      sym_bare_z,
  [141] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      sym_trigger_name,
      sym_text,
    ACTIONS(115), 5,
      sym_function_start,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      sym_newline,
      sym_bare_z,
  [156] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      sym_trigger_name,
      sym_text,
    ACTIONS(123), 5,
      sym_function_start,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      sym_newline,
      sym_bare_z,
  [171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
  [178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
  [185] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_newline,
  [192] = 2,
    ACTIONS(141), 1,
      aux_sym_header_token2,
    ACTIONS(143), 1,
      sym_comment,
  [199] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
  [206] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LBRACE,
  [213] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 16,
  [SMALL_STATE(17)] = 32,
  [SMALL_STATE(18)] = 48,
  [SMALL_STATE(19)] = 64,
  [SMALL_STATE(20)] = 80,
  [SMALL_STATE(21)] = 96,
  [SMALL_STATE(22)] = 111,
  [SMALL_STATE(23)] = 126,
  [SMALL_STATE(24)] = 141,
  [SMALL_STATE(25)] = 156,
  [SMALL_STATE(26)] = 171,
  [SMALL_STATE(27)] = 178,
  [SMALL_STATE(28)] = 185,
  [SMALL_STATE(29)] = 192,
  [SMALL_STATE(30)] = 199,
  [SMALL_STATE(31)] = 206,
  [SMALL_STATE(32)] = 213,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_content, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_content, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_call, 3, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger_call, 3, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_call, 4, 0, 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger_call, 4, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_content, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_content, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_function_start = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_function_start] = sym_function_start,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_function_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_zbr_external_scanner_create(void);
void tree_sitter_zbr_external_scanner_destroy(void *);
bool tree_sitter_zbr_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_zbr_external_scanner_serialize(void *, char *);
void tree_sitter_zbr_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zbr(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_zbr_external_scanner_create,
      tree_sitter_zbr_external_scanner_destroy,
      tree_sitter_zbr_external_scanner_scan,
      tree_sitter_zbr_external_scanner_serialize,
      tree_sitter_zbr_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "zbr",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
